version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Expose Prometheus UI on port 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount Prometheus configuration file
    restart: always
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Expose Grafana UI on port 3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set the default admin password
    volumes:
      - grafana-data:/var/lib/grafana  # Persist Grafana data
    restart: always
    depends_on:
      - prometheus
    networks:
      - monitoring-network

volumes:
  grafana-data:
    driver: local

networks:
  monitoring-network:
    driver: bridge

